@php
  $pclass = $pclass ?? '';
  $h4class = $h4class ?? '';
  $h5class = $h5class ?? '';
  $ulclass = $ulclass ?? '';
  $liclass = $liclass ?? '';
@endphp

<h4 class="{{ $h4class }}">Objectives</h4>
<p class="{{ $pclass }}">The 70th Australian Intervarsity Choral Festival (AIV) is intended to be a fun and safe environment for all attendees. This code of conduct has been designed to:</p>
<ul class="{{ $ulclass }}">
  <li class="{{ $liclass }}">Clarify good conduct and inappropriate behaviour</li>
  <li class="{{ $liclass }}">Explicate standards of behaviour expected of members of the Festival</li>
  <li class="{{ $liclass }}">Provide options for managing inappropriate behaviour</li>
</ul>
<p class="{{ $pclass }}">By attending the Festival you agree to comply with this Code of Conduct and accept its conditions. Please note that failure to comply with the Code of Conduct may result in ejection from the Festival at the discretion of the Festival Committee.</p>
<h4 class="{{ $h4class }}">Definitions</h4>
<h5 class="{{ $h5class }}">Good Conduct</h5>
<p class="{{ $pclass }}">All members of the Festival are expected to behave in a way that ensures other members are able to feel safe.</p>
<p class="{{ $pclass }}">Good conduct includes, but is not limited to:</p>
<ul class="{{ $ulclass }}">
  <li class="{{ $liclass }}">Respecting the rights of others;</li>
  <li class="{{ $liclass }}">Behaving honestly and with integrity;</li>
  <li class="{{ $liclass }}">Acting with care and diligence; and</li>
  <li class="{{ $liclass }}">Treating others with respect and courtesy, without harassment.</li>
</ul>
<h5 class="{{ $h5class }}">Discrimination</h5>
<p class="{{ $pclass }}">Refers to the less favourable treatment of a person by another or others based on their actual or perceived membership in a certain group or category.</p>
<p class="{{ $pclass }}">This does not include cases where such treatment is required by law or is necessary for the safety of others.</p>
<h5 class="{{ $h5class }}">Harassment</h5>
<p class="{{ $pclass }}">Refers to the repeated less favourable treatment of a person by another or others. This includes any persistent unwelcome behaviour, particularly unwarranted or invalid criticism, fault finding, exclusion or isolation. It can make participating in activities humiliating or intimidating for the individual or group targeted by this behaviour. The Festival does not tolerate any form of harassment.</p>
<p class="{{ $pclass }}">Harassment does not include differences of opinion or non-aggressive conflict.</p>
<p class="{{ $pclass }}">Behaviour will only be defined as harassment if an objective third party observing the situation would consider it to be harassment.</p>
<h5 class="{{ $h5class }}">Violent Behaviour</h5>
<p class="{{ $pclass }}">Refers to behaviour that has or is likely to cause injury or damage to persons or property, whether such persons or property are affiliated with the Festival or not.</p>
<h4 class="{{ $h4class }}">Principles of Good Behaviour</h4>
<p class="{{ $pclass }}">All members have the responsibility of ensuring that they behave with good conduct.</p>
<p class="{{ $pclass }}">Every member of the Festival can expect certain rights, and Good Conduct begins with respecting these rights. In particular, some basic principles should be taken into consideration, including the following.</p>
<h5 class="{{ $h5class }}">Privacy</h5>
<p class="{{ $pclass }}">While AIV is a public event, recording events without the consent of the participants can make some people feel that their privacy has been violated. It is appropriate to ask permission before taking and uploading photographs to the Internet, quoting people on Social Media, etc.</p>
<p class="{{ $pclass }}">In addition, while some members may feel comfortable broaching delicate or personal subjects, others may not. It is appropriate to accept someone’s refusal to divulge information about themselves with good grace, and move on.</p>
<h5 class="{{ $h5class }}">Personal Boundaries</h5>
<p class="{{ $pclass }}">People’s attitudes towards personal boundaries can vary widely. For example, while some people may be okay with hugs for greeting and casual physical contact, others may not. It is appropriate to ask permission before making contact with someone or coming very close to them.</p>
<p class="{{ $pclass }}">In particular, it may not always be clear when a long-standing relationship means that a person has implicit permission to enter another’s personal space. Even if someone is making contact with someone else, it is appropriate to ask before taking the same liberty.</p>
<h5 class="{{ $h5class }}">Veracity</h5>
<p class="{{ $pclass }}">Where possible, honesty really is the best policy. False statements, particularly made about other people, can cause significant hurt to people in particular, and damage to the culture of the Festival as a whole. If you don’t know what to say, or don’t feel comfortable sharing the truth about something, it is appropriate to say nothing at all.</p>
<h5 class="{{ $h5class }}">Encouragement</h5>
<p class="{{ $pclass }}">Intervarsity Choral Festivals bring together a wide range of people from a variety of different backgrounds, educational levels and knowledge. It is an opportunity for people of all skill levels to come together and learn as well as have fun. Even if someone does not have knowledge or skills that you have, it is appropriate to give friendly and honest feedback, and encourage the development of skills and talents.</p>
<h4 class="{{ $h4class }}">Types of Inappropriate Behaviour</h4>
<p class="{{ $pclass }}">The following are some examples of specific types of inappropriate behaviour. This should not be taken as an exhaustive list.</p>
<h5 class="{{ $h5class }}">Abuse of Drugs</h5>
<p class="{{ $pclass }}">While the consumption of alcohol may serve as a welcome means of relaxation and enjoyment for members, the abuse of alcohol by drinking to excess is inappropriate behaviour throughout the Festival.</p>
<p class="{{ $pclass }}">The possession or use of illicit drugs, or the illegal supply of drugs to minors, will not be tolerated. Immediate expulsion from the Festival and referral to relevant authorities will result.</p>
<h5 class="{{ $h5class }}">Bullying</h5>
<p class="{{ $pclass }}">Bullying may be characterised as offensive, intimidating, malicious or insulting behaviour, an abuse or misuse of power through means intended to undermine, humiliate, denigrate or injure the recipient. Examples of bullying could be:</p>
<ul class="{{ $ulclass }}">
  <li class="{{ $liclass }}">Abuse of power or authority</li>
  <li class="{{ $liclass }}">Verbal, written and/or physical intimidation e.g. threats, derisory remarks</li>
  <li class="{{ $liclass }}">Persistent unjustified criticism</li>
  <li class="{{ $liclass }}">Public humiliation</li>
  <li class="{{ $liclass }}">The setting of impossible deadlines or intolerable workload burdens</li>
  <li class="{{ $liclass }}">Having responsibilities or decision-making powers withdrawn without good reason or explanation</li>
  <li class="{{ $liclass }}">Unwarranted exclusions</li>
</ul>
<p class="{{ $pclass }}">Vigorous speech, comment or academic debate can be distinguished from bullying behaviour. In these situations, care should be taken to ensure that staff, volunteers and Festival members are not made to feel intimidated.</p>
<p class="{{ $pclass }}">The bullying of staff, volunteers or members of the Festival is inappropriate, and may result in expulsion from the Festival.</p>
<h5 class="{{ $h5class }}">Sexual Harassment</h5>
<p class="{{ $pclass }}">Sexual harassment is defined as any form of unwanted verbal, non-verbal or physical conduct of a sexual nature that creates an intimidating, hostile, degrading or offensive environment. It may include:</p>
<ul class="{{ $ulclass }}">
  <li class="{{ $liclass }}">Physical contact</li>
  <li class="{{ $liclass }}">Invasion of personal space</li>
  <li class="{{ $liclass }}">Suggestive remarks or sounds</li>
  <li class="{{ $liclass }}">Unwanted comments on dress and appearance</li>
  <li class="{{ $liclass }}">Jokes of a sexual nature</li>
  <li class="{{ $liclass }}">Display of sexually offensive material</li>
  <li class="{{ $liclass }}">Inappropriate downloading of material</li>
  <li class="{{ $liclass }}">Verbal threats</li>
</ul>
<p class="{{ $pclass }}">It is important to remember that sexual harassment can occur towards women by men, men by women, and also between members of the same sex. It can also refer to unwanted conduct that is related to the sex of the other person.</p>
<p class="{{ $pclass }}">Sexual Harassment is taken very seriously by the Festival Committee, and may result in expulsion from the Festival.</p>
<h5 class="{{ $h5class }}">Discrimination</h5>
<p class="{{ $pclass }}">Discrimination refers to the less favourable treatment of a person by another or others based on their actual or perceived membership in a certain group or category. In particular, it may include treatment based on a person’s actual or perceived:</p>
<ul class="{{ $ulclass }}">
  <li class="{{ $liclass }}">Age</li>
  <li class="{{ $liclass }}">Race/Ethnicity</li>
  <li class="{{ $liclass }}">Nationality</li>
  <li class="{{ $liclass }}">Disability</li>
  <li class="{{ $liclass }}">Sex</li>
  <li class="{{ $liclass }}">Sexual Orientation</li>
  <li class="{{ $liclass }}">Gender Identity</li>
  <li class="{{ $liclass }}">Language</li>
  <li class="{{ $liclass }}">Religious Belief or otherwise</li>
</ul>
<p class="{{ $pclass }}">Restrictions imposed for legal or safety reasons, such as the restriction of certain events to members over the age of eighteen as required by Australian law, are legitimate. However, discrimination where no legitimate reason is present is inappropriate behaviour.</p>
<p class="{{ $pclass }}">Repeated discrimination constitutes harassment, and may result in expulsion from the Festival.</p>
<h5 class="{{ $h5class }}">Violent and threatening behaviour</h5>
<p class="{{ $pclass }}">Violent behaviours or threats of violence, including to persons, property or self, are a significant risk to the Festival and its members.</p>
<p class="{{ $pclass }}">As such, a no-tolerance policy applies to violence or threats of violence, and appropriate authorities may be engaged at the discretion of the Festival.</p>
<h4 class="{{ $h4class }}">Equity Officers</h4>
<p class="{{ $pclass }}">If a member feels harassed or discriminated against, and they feel comfortable doing so, they may ask the person to stop or make it clear that their behaviour is unwelcome.</p>
<p class="{{ $pclass }}">In order to deal with cases where this is not sufficient, however, the Festival Committee shall appoint Equity Officers, who shall serve as a point of contact during the Festival. Contact details for the Equity Officers shall be made available to all members of the Festival.</p>
<p class="{{ $pclass }}">When appointing Equity Officers, care will be taken to ensure that they are (as much as is practicable) sensible, respected and approachable members of the broader IV community. The Officers shall not be members of the Festival Committee.</p>
<p class="{{ $pclass }}">The Officers have the full support of the Festival Committee in all aspects of their role, however the Committee may remove an Equity Officer where warranted.</p>
<p class="{{ $pclass }}">The Equity Officers may take whatever action they deem practicable to deal with complaints of inappropriate behaviour. This may include discussing the inappropriate behaviour with both parties with an aim to find an amicable solution.</p>
<p class="{{ $pclass }}">If, in the opinion of the Equity Officers, inappropriate behaviour is unlikely to be manageable amicably, they may recommend to the Festival Committee that a person be ejected from the Festival.</p>

